### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lucaterre** [chartes/Nakalator#1]
- [x] Relire et corriger le Readme.md
- [x] Ajouter temps d'execution
- [x] Attention: docstrings a revoir sur nkl_gotils.py
- [x] Refaire un test en local 
- [x] tests utilisateurs (adapter Readme et la template en fonction)
- [x] Relire le Readme + push
- [x] Ajouter les dist sur Pypi + ajout de la release sur GH + badge dans Readme
- [ ] Dqp : Ajouter les tests et GH actions
- [ ] Dqp : Ajouter le dossier `examples/` avec des structures de projet différentes (référence dans le readme)
- [ ] Dqp : ajouter le dossier `scripts/` (référence dans le readme) : préparer les fichiers de métadonnées YAML en lot et l'arborescence attaché, modifier / ajouter / supprimer les métadonnées en lot sur Nakala, rendre publique et publier données et collections en lot sur Nakala  
- [ ] Dqp : Readme en version anglaise ? 
- [ ] Dqp : construire un GH actions pour faire la compilation des sources Go dans une matrice ??

**Comment by Lucaterre** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Nakalator](https://trello.com/c/ehwsK5KZ/146-nakalator)
